import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET(req: Request) {
  const url = new URL(req.url);
  const baseUrl = `${url.protocol}//${url.host}`;

  return NextResponse.json({
    name: 'x-manager',
    description: 'Local X (Twitter) account connector + tweet scheduler (supports threads, replies, media, dedupe).',
    baseUrl,
    ui: `${baseUrl}/`,
    quickstart: {
      start: 'npm run dev:ensure',
      status: 'npm run dev:status',
      logs: 'npm run dev:logs',
      stop: 'npm run dev:stop',
      systemd: {
        install: 'npm run install:systemd-user',
        start: 'systemctl --user start x-manager.service',
        stop: 'systemctl --user stop x-manager.service',
        status: 'systemctl --user status x-manager.service --no-pager',
        logs: 'journalctl --user -u x-manager.service -n 200 --no-pager',
        cli: 'x-manager start',
      },
      url: 'http://127.0.0.1:3999',
      note: 'By default the server binds to 127.0.0.1 for safety. Use SSH port-forwarding if you need to access it remotely.',
    },
    coreEndpoints: [
      {
        id: 'readiness',
        method: 'GET',
        path: '/api/system/readiness',
        description: 'Health/readiness check including connected X slots and scheduler state.',
      },
      {
        id: 'auth_login',
        method: 'POST',
        path: '/api/system/auth/login',
        contentType: 'application/json',
        description: 'Create an authenticated admin session cookie using X_MANAGER_ADMIN_TOKEN.',
      },
      {
        id: 'auth_session',
        method: 'GET',
        path: '/api/system/auth/session',
        description: 'Return current API/UI auth session state.',
      },
      {
        id: 'list_posts',
        method: 'GET',
        path: '/api/scheduler/posts',
        description: 'List scheduled posts (optionally filter by ?account_slot=1|2).',
      },
      {
        id: 'schedule_post',
        method: 'POST',
        path: '/api/scheduler/posts',
        contentType: 'multipart/form-data',
        description:
          'Schedule a single post (supports replies + media). Dedupe: if same canonical URL + same copy is already scheduled for that slot, returns the existing post.',
        fields: [
          { name: 'text', required: true },
          { name: 'scheduled_time', required: true, format: 'ISO string' },
          { name: 'account_slot', required: false, default: 1, allowed: [1, 2] },
          { name: 'community_id', required: false },
          { name: 'reply_to_tweet_id', required: false },
          { name: 'files', required: false, repeatable: true, note: 'Up to 4 images/GIFs.' },
          { name: 'thread_id', required: false, note: 'If set, groups this post into a thread.' },
          { name: 'thread_index', required: false, note: '0-based position in thread. Requires thread_id.' },
          { name: 'source_url', required: false, note: 'Optional URL override for dedupe/canonicalization.' },
        ],
      },
      {
        id: 'upload_media',
        method: 'POST',
        path: '/api/scheduler/media',
        contentType: 'multipart/form-data',
        description: 'Upload media to /public/uploads and return mediaUrls you can reference in thread scheduling.',
        fields: [{ name: 'files', required: true, repeatable: true, note: 'Up to 4 files.' }],
      },
      {
        id: 'schedule_thread',
        method: 'POST',
        path: '/api/scheduler/thread',
        contentType: 'application/json',
        description:
          'Schedule a thread as a group (stored as multiple scheduled_posts rows with thread_id/thread_index). If dedupe finds any tweet in the thread already scheduled (same URL+copy), the whole thread is skipped.',
      },
      {
        id: 'create_thread',
        method: 'POST',
        path: '/api/agent/create-thread',
        contentType: 'application/json',
        description:
          'Create a media-aware thread draft from an article URL (extracts quote candidates + article images, downloads images into /uploads). Optional one-shot scheduling when schedule=true.',
        fields: [
          { name: 'article_url', required: true, note: 'Public article URL (e.g. swarmsignal.net post).' },
          { name: 'account_slot', required: false, default: 1, allowed: [1, 2] },
          { name: 'max_tweets', required: false, default: 6, note: 'Range 2..12' },
          { name: 'include_images', required: false, default: true },
          { name: 'schedule', required: false, default: false },
          { name: 'scheduled_time', required: false, format: 'ISO string', note: 'Required only when schedule=true.' },
          { name: 'dedupe', required: false, default: true },
          { name: 'community_id', required: false },
          { name: 'reply_to_tweet_id', required: false },
        ],
      },
      {
        id: 'openclaw_bridge_post',
        method: 'POST',
        path: '/api/bridge/openclaw/post',
        contentType: 'application/json',
        description:
          'Bridge endpoint for external bots (e.g. OpenClaw) to publish immediately via a connected X slot. Requires Authorization: Bearer <OPENCLAW_BRIDGE_TOKEN>; supports optional signed requests via x-openclaw-timestamp + x-openclaw-signature.',
        fields: [
          { name: 'text|content|message|tweet_text', required: true, note: 'Any one can supply tweet text.' },
          { name: 'account_slot|slot', required: false, default: 1, allowed: [1, 2] },
          { name: 'account|handle|username', required: false, note: 'Alternative to slot (e.g. "swarm_signal").' },
          { name: 'media_urls|mediaUrls|images', required: false, note: 'Up to 4 image URLs or /uploads paths.' },
          { name: 'community_id|communityId', required: false },
          { name: 'reply_to_tweet_id|replyToTweetId|reply_to', required: false },
          { name: 'dry_run|dryRun|simulate', required: false, default: false },
        ],
      },
      {
        id: 'engagement_sync',
        method: 'POST',
        path: '/api/engagement/inbox/sync',
        contentType: 'application/json',
        description: 'Pull mentions and/or DMs for a slot and upsert them into the local engagement inbox.',
      },
      {
        id: 'engagement_inbox',
        method: 'GET',
        path: '/api/engagement/inbox',
        description: 'List local engagement inbox items with optional filters (slot/type/status).',
      },
      {
        id: 'engagement_reply',
        method: 'POST',
        path: '/api/engagement/actions/reply',
        contentType: 'application/json',
        description: 'Send an immediate reply to a tweet and optionally mark an inbox item as replied.',
      },
      {
        id: 'engagement_dm',
        method: 'POST',
        path: '/api/engagement/actions/dm',
        contentType: 'application/json',
        description: 'Send an immediate direct message via a connected slot.',
      },
      {
        id: 'agent_campaigns',
        method: 'GET/POST',
        path: '/api/agent/campaigns',
        description: 'Create and list campaign orchestration containers (goal, date window, slot, status).',
      },
      {
        id: 'agent_campaign_plan',
        method: 'POST',
        path: '/api/agent/campaigns/:id/plan',
        description: 'Generate a default agent execution plan for a campaign and optionally persist tasks.',
      },
      {
        id: 'agent_campaign_tasks',
        method: 'GET/POST',
        path: '/api/agent/campaigns/:id/tasks',
        description: 'List or create campaign tasks.',
      },
      {
        id: 'agent_approvals',
        method: 'GET/POST/PATCH',
        path: '/api/agent/approvals',
        description: 'Create/list/decide approval checkpoints for campaign tasks.',
      },
      {
        id: 'agent_task_execute',
        method: 'POST',
        path: '/api/agent/tasks/:id/execute',
        contentType: 'application/json',
        description: 'Execute a single campaign task. Supports dry_run mode and Idempotency-Key header.',
        fields: [
          { name: 'dry_run', required: false, default: false },
          { name: 'Idempotency-Key', required: false, note: 'HTTP header for idempotent execution.' },
        ],
      },
      {
        id: 'agent_campaign_execute',
        method: 'POST',
        path: '/api/agent/campaigns/:id/execute',
        contentType: 'application/json',
        description: 'Execute all eligible tasks in a campaign. Supports dry_run and max_tasks limit.',
        fields: [
          { name: 'dry_run', required: false, default: false },
          { name: 'max_tasks', required: false, note: 'Limit number of tasks to execute in one call.' },
        ],
      },
      {
        id: 'agent_runs_list',
        method: 'GET',
        path: '/api/agent/runs',
        description: 'List execution runs with optional filters (campaign_id, status).',
      },
      {
        id: 'agent_run_detail',
        method: 'GET',
        path: '/api/agent/runs/:id',
        description: 'Get detailed run information including execution steps.',
      },
      {
        id: 'actions_list',
        method: 'GET',
        path: '/api/actions',
        description: 'List scheduled actions with optional filters (account_slot, status).',
      },
      {
        id: 'actions_schedule',
        method: 'POST',
        path: '/api/actions',
        contentType: 'application/json',
        description: 'Schedule a new action (like, reply, dm, repost).',
        fields: [
          { name: 'action_type', required: true, allowed: ['like', 'reply', 'dm', 'repost'] },
          { name: 'account_slot', required: true },
          { name: 'scheduled_time', required: true, format: 'ISO string' },
          { name: 'target_tweet_id', required: false, note: 'Required for like/reply/repost.' },
          { name: 'target_user_id', required: false, note: 'Required for dm.' },
          { name: 'text', required: false, note: 'Required for reply/dm.' },
        ],
      },
      {
        id: 'action_detail',
        method: 'GET',
        path: '/api/actions/:id',
        description: 'Get detailed information about a scheduled action.',
      },
      {
        id: 'action_cancel',
        method: 'DELETE',
        path: '/api/actions/:id',
        description: 'Cancel a scheduled action (only if status is pending).',
      },
      {
        id: 'action_retry',
        method: 'POST',
        path: '/api/actions/retry',
        contentType: 'application/json',
        description: 'Retry a failed action.',
        fields: [{ name: 'action_id', required: true }],
      },
      {
        id: 'policy_get',
        method: 'GET',
        path: '/api/agent/policy',
        description: 'Get slot policy configuration (quotas, time windows). Use ?slot=1 query param.',
      },
      {
        id: 'policy_update',
        method: 'PUT',
        path: '/api/agent/policy',
        contentType: 'application/json',
        description: 'Update slot policy configuration (quotas, allowed hours).',
      },
      {
        id: 'policy_check',
        method: 'POST',
        path: '/api/agent/policy',
        contentType: 'application/json',
        description: 'Check if an action is allowed by current policy.',
        fields: [
          { name: 'account_slot', required: true },
          { name: 'action_type', required: true },
        ],
      },
      {
        id: 'usage_api_calls',
        method: 'GET',
        path: '/api/usage/api-calls',
        description: 'List API call logs with aggregation summary. Supports date range and grouping filters.',
      },
      {
        id: 'drafts_list',
        method: 'GET',
        path: '/api/drafts',
        description: 'List drafts with optional account_slot filter.',
      },
      {
        id: 'drafts_create',
        method: 'POST',
        path: '/api/drafts',
        contentType: 'application/json',
        description: 'Create a new draft.',
        fields: [
          { name: 'account_slot', required: true },
          { name: 'content', required: true },
          { name: 'metadata', required: false, note: 'JSON object with additional draft data.' },
        ],
      },
      {
        id: 'draft_detail',
        method: 'GET',
        path: '/api/drafts/:id',
        description: 'Get detailed information about a draft.',
      },
      {
        id: 'draft_update',
        method: 'PUT',
        path: '/api/drafts/:id',
        contentType: 'application/json',
        description: 'Update an existing draft.',
      },
      {
        id: 'draft_delete',
        method: 'DELETE',
        path: '/api/drafts/:id',
        description: 'Delete a draft.',
      },
      {
        id: 'templates_list',
        method: 'GET',
        path: '/api/templates',
        description: 'List all templates.',
      },
      {
        id: 'templates_create',
        method: 'POST',
        path: '/api/templates',
        contentType: 'application/json',
        description: 'Create a new template.',
        fields: [
          { name: 'name', required: true },
          { name: 'content', required: true },
          { name: 'variables', required: false, note: 'Array of variable names used in template.' },
        ],
      },
      {
        id: 'template_update',
        method: 'PUT',
        path: '/api/templates/:id',
        contentType: 'application/json',
        description: 'Update an existing template.',
      },
      {
        id: 'template_delete',
        method: 'DELETE',
        path: '/api/templates/:id',
        description: 'Delete a template.',
      },
      {
        id: 'inbox_tags_list',
        method: 'GET',
        path: '/api/engagement/inbox/:id/tags',
        description: 'List all tags for an inbox item.',
      },
      {
        id: 'inbox_tag_add',
        method: 'POST',
        path: '/api/engagement/inbox/:id/tags',
        contentType: 'application/json',
        description: 'Add a tag to an inbox item.',
        fields: [{ name: 'tag', required: true }],
      },
      {
        id: 'inbox_tag_remove',
        method: 'DELETE',
        path: '/api/engagement/inbox/:id/tags',
        description: 'Remove a tag from inbox item. Use ?tag=X query param.',
      },
      {
        id: 'inbox_notes_list',
        method: 'GET',
        path: '/api/engagement/inbox/:id/notes',
        description: 'List all notes for an inbox item.',
      },
      {
        id: 'inbox_note_add',
        method: 'POST',
        path: '/api/engagement/inbox/:id/notes',
        contentType: 'application/json',
        description: 'Add a note to an inbox item.',
        fields: [{ name: 'text', required: true }],
      },
      {
        id: 'inbox_assign',
        method: 'PUT',
        path: '/api/engagement/inbox/:id/assign',
        contentType: 'application/json',
        description: 'Assign an inbox item to a user or team.',
        fields: [{ name: 'assigned_to', required: true }],
      },
      {
        id: 'inbox_conversations',
        method: 'GET',
        path: '/api/engagement/inbox/conversations',
        description: 'Get conversation view of inbox items grouped by thread.',
      },
    ],
    curlExamples: {
      readiness: `curl -sS ${baseUrl}/api/system/readiness`,
      authLogin: `curl -sS -X POST ${baseUrl}/api/system/auth/login \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"token\":\"'$X_MANAGER_ADMIN_TOKEN'\"}'`,
      scheduleSingle: `curl -sS -X POST ${baseUrl}/api/scheduler/posts \\\n  -F account_slot=1 \\\n  -F scheduled_time=\"2026-02-10T09:00:00Z\" \\\n  -F text=\"Hello world https://example.com\"`,
      scheduleReply: `curl -sS -X POST ${baseUrl}/api/scheduler/posts \\\n  -F account_slot=1 \\\n  -F scheduled_time=\"2026-02-10T09:00:00Z\" \\\n  -F reply_to_tweet_id=\"1234567890\" \\\n  -F text=\"Replying with a link https://example.com\"`,
      scheduleWithImage: `curl -sS -X POST ${baseUrl}/api/scheduler/posts \\\n  -F account_slot=1 \\\n  -F scheduled_time=\"2026-02-10T09:00:00Z\" \\\n  -F text=\"With image https://example.com\" \\\n  -F files=@/absolute/path/to/image.jpg`,
      uploadMedia: `curl -sS -X POST ${baseUrl}/api/scheduler/media \\\n  -F files=@/absolute/path/to/image1.jpg \\\n  -F files=@/absolute/path/to/image2.png`,
      scheduleThreadJson: `curl -sS -X POST ${baseUrl}/api/scheduler/thread \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"account_slot\": 1,\n    \"scheduled_time\": \"2026-02-10T09:00:00Z\",\n    \"dedupe\": true,\n    \"tweets\": [\n      {\"text\": \"Thread part 1 https://example.com\", \"media_urls\": [\"/uploads/your-file.jpg\"]},\n      {\"text\": \"Thread part 2\"}\n    ]\n  }'`,
      createThreadDraft: `curl -sS -X POST ${baseUrl}/api/agent/create-thread \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"article_url\": \"https://swarmsignal.net/example-post/\",\n    \"account_slot\": 1,\n    \"max_tweets\": 6,\n    \"include_images\": true,\n    \"schedule\": false\n  }'`,
      createAndScheduleThread: `curl -sS -X POST ${baseUrl}/api/agent/create-thread \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"article_url\": \"https://swarmsignal.net/example-post/\",\n    \"account_slot\": 1,\n    \"scheduled_time\": \"2026-02-12T09:00:00Z\",\n    \"schedule\": true,\n    \"dedupe\": true\n  }'`,
      openclawBridgePost: `curl -sS -X POST ${baseUrl}/api/bridge/openclaw/post \\\n  -H \"Authorization: Bearer $OPENCLAW_BRIDGE_TOKEN\" \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"content\": \"Bridge post from OpenClaw\",\n    \"account\": \"swarm_signal\",\n    \"images\": [\"/uploads/example.jpg\"],\n    \"dryRun\": false\n  }'`,
      openclawBridgeSignedPost: `BODY='{\"content\":\"Bridge post from OpenClaw\",\"account\":\"swarm_signal\",\"images\":[],\"dryRun\":true}'\nTS=\"$(date +%s)\"\nSIG=\"$(printf '%s' \"$TS.$BODY\" | openssl dgst -sha256 -hmac \"$OPENCLAW_BRIDGE_SIGNING_SECRET\" -hex | awk '{print $2}')\"\ncurl -sS -X POST ${baseUrl}/api/bridge/openclaw/post \\\n  -H \"Authorization: Bearer $OPENCLAW_BRIDGE_TOKEN\" \\\n  -H \"x-openclaw-timestamp: $TS\" \\\n  -H \"x-openclaw-signature: $SIG\" \\\n  -H 'Content-Type: application/json' \\\n  -d \"$BODY\"`,
      syncInbox: `curl -sS -X POST ${baseUrl}/api/engagement/inbox/sync \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"account_slot\":1,\"include_mentions\":true,\"include_dms\":true,\"count\":25}'`,
      listInbox: `curl -sS '${baseUrl}/api/engagement/inbox?account_slot=1&type=mention&status=new'`,
      sendReply: `curl -sS -X POST ${baseUrl}/api/engagement/actions/reply \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"account_slot\":1,\"reply_to_tweet_id\":\"1234567890\",\"text\":\"Thanks for sharing this.\"}'`,
      sendDm: `curl -sS -X POST ${baseUrl}/api/engagement/actions/dm \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"account_slot\":1,\"recipient_user_id\":\"12345\",\"text\":\"Thanks for reaching out.\"}'`,
      createCampaign: `curl -sS -X POST ${baseUrl}/api/agent/campaigns \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"name\":\"Q2 Launch\",\"objective\":\"Drive qualified demo requests\",\"account_slot\":1,\"status\":\"active\"}'`,
      buildCampaignPlan: `curl -sS -X POST ${baseUrl}/api/agent/campaigns/1/plan \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"save\":true}'`,
      createApproval: `curl -sS -X POST ${baseUrl}/api/agent/approvals \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"campaign_id\":1,\"task_id\":2,\"requested_by\":\"agent\"}'`,
      executeTask: `curl -sS -X POST ${baseUrl}/api/agent/tasks/1/execute \\\n  -H 'Content-Type: application/json' \\\n  -H 'Idempotency-Key: task-1-exec-20260215' \\\n  -d '{\"dry_run\":false}'`,
      executeCampaign: `curl -sS -X POST ${baseUrl}/api/agent/campaigns/1/execute \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"dry_run\":false,\"max_tasks\":5}'`,
      listRuns: `curl -sS '${baseUrl}/api/agent/runs?campaign_id=1&status=completed'`,
      getRunDetail: `curl -sS ${baseUrl}/api/agent/runs/1`,
      listActions: `curl -sS '${baseUrl}/api/actions?account_slot=1&status=pending'`,
      scheduleAction: `curl -sS -X POST ${baseUrl}/api/actions \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"action_type\":\"like\",\"account_slot\":1,\"scheduled_time\":\"2026-02-16T10:00:00Z\",\"target_tweet_id\":\"1234567890\"}'`,
      scheduleReplyAction: `curl -sS -X POST ${baseUrl}/api/actions \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"action_type\":\"reply\",\"account_slot\":1,\"scheduled_time\":\"2026-02-16T10:00:00Z\",\"target_tweet_id\":\"1234567890\",\"text\":\"Great point!\"}'`,
      scheduleDmAction: `curl -sS -X POST ${baseUrl}/api/actions \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"action_type\":\"dm\",\"account_slot\":1,\"scheduled_time\":\"2026-02-16T10:00:00Z\",\"target_user_id\":\"12345\",\"text\":\"Thanks for connecting.\"}'`,
      getActionDetail: `curl -sS ${baseUrl}/api/actions/1`,
      cancelAction: `curl -sS -X DELETE ${baseUrl}/api/actions/1`,
      retryAction: `curl -sS -X POST ${baseUrl}/api/actions/retry \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"action_id\":1}'`,
      getPolicy: `curl -sS '${baseUrl}/api/agent/policy?slot=1'`,
      updatePolicy: `curl -sS -X PUT ${baseUrl}/api/agent/policy \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"account_slot\":1,\"max_posts_per_hour\":5,\"max_replies_per_hour\":10,\"allowed_hours\":[9,10,11,12,13,14,15,16,17]}'`,
      checkPolicy: `curl -sS -X POST ${baseUrl}/api/agent/policy \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"account_slot\":1,\"action_type\":\"post\"}'`,
      listApiCalls: `curl -sS '${baseUrl}/api/usage/api-calls?start_date=2026-02-01&end_date=2026-02-15'`,
      listDrafts: `curl -sS '${baseUrl}/api/drafts?account_slot=1'`,
      createDraft: `curl -sS -X POST ${baseUrl}/api/drafts \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"account_slot\":1,\"content\":\"Draft tweet content\",\"metadata\":{\"source\":\"agent\"}}'`,
      getDraft: `curl -sS ${baseUrl}/api/drafts/1`,
      updateDraft: `curl -sS -X PUT ${baseUrl}/api/drafts/1 \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"content\":\"Updated draft content\"}'`,
      deleteDraft: `curl -sS -X DELETE ${baseUrl}/api/drafts/1`,
      listTemplates: `curl -sS ${baseUrl}/api/templates`,
      createTemplate: `curl -sS -X POST ${baseUrl}/api/templates \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"name\":\"Welcome DM\",\"content\":\"Hi {{name}}, thanks for following!\",\"variables\":[\"name\"]}'`,
      updateTemplate: `curl -sS -X PUT ${baseUrl}/api/templates/1 \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"content\":\"Hi {{name}}, welcome to our community!\"}'`,
      deleteTemplate: `curl -sS -X DELETE ${baseUrl}/api/templates/1`,
      listInboxTags: `curl -sS ${baseUrl}/api/engagement/inbox/1/tags`,
      addInboxTag: `curl -sS -X POST ${baseUrl}/api/engagement/inbox/1/tags \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"tag\":\"important\"}'`,
      removeInboxTag: `curl -sS -X DELETE '${baseUrl}/api/engagement/inbox/1/tags?tag=important'`,
      listInboxNotes: `curl -sS ${baseUrl}/api/engagement/inbox/1/notes`,
      addInboxNote: `curl -sS -X POST ${baseUrl}/api/engagement/inbox/1/notes \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"text\":\"Follow up next week\"}'`,
      assignInbox: `curl -sS -X PUT ${baseUrl}/api/engagement/inbox/1/assign \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"assigned_to\":\"team-support\"}'`,
      getConversations: `curl -sS ${baseUrl}/api/engagement/inbox/conversations`,
    },
    notes: [
      'When X_MANAGER_REQUIRE_AUTH=true, authenticate via /api/system/auth/login or send Authorization: Bearer <X_MANAGER_ADMIN_TOKEN> on API calls.',
      'Link previews are controlled by X: include a URL in the text to get a card/preview.',
      'Attaching your own images usually shows the image instead of the link card. X does not provide an API to replace a link-card preview image while keeping the card.',
    ],
  });
}
